## Create & Add a Long Live Access Token to secrets
## https://appdaemon.readthedocs.io/en/latest/CONFIGURE.html#secrets
secrets: /home/hass/homeassistant/secrets.yaml

# https://appdaemon.readthedocs.io/en/latest/INSTALL.html#configuration
appdaemon:
  # disable_apps: 1
  latitude: 41.024250
  longitude: -80.614595
  elevation: 321
  time_zone: America/New_York
  threads: 10
  production_mode: true
  app_dir: /home/hass/appdaemon/apps
  plugins:
    HASS:
      type: hass
      ha_url: http://127.0.0.1:8123
      token: !secret appdaemon_token
hadashboard:
  dash_url: http://127.0.0.1:5050
  dashboard_dir: /home/hass/appdaemon/dashboards
